<a href="https://colab.research.google.com/github/Ayryslaine/analise_desigualdade_educacional/blob/main/analise_desigualdade_educacional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perguntas que serão respondidas

Tipo de escola por Estado

Grupos minoritários por tipo de escola

Percentual de Evasão

Percentual de evasão por tipo de escola

Nível de evasão por escolaridade

Nível de evasão de estudantes de baixa renda

Média de Estudantes por professor

Nível de acesso à internet por tipo de escola

Financiamento por nível de escolaridade

Financiamento por tipo de escola

Porcentagem de estudantes de baixa-renda

# Importação do banco de dados e bibliotecas

In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/education_inequality_data.csv", sep= ",")

Visualização de nosso banco de dados:

In [48]:
display(df)

,id,school_name,state,school_type,grade_level,funding_per_student_usd,avg_test_score_percent,student_teacher_ratio,percent_low_income,percent_minority,internet_access_percent,dropout_rate_percent
0,1,Bowman High School,Michigan,Private,High,9575.80,65.9,17.5,30.0,44.0,74.1,3.44
1,2,Foster High School,Michigan,Charter,Middle,16733.10,87.3,24.2,93.5,40.1,79.9,8.67
2,3,Henson High School,New York,Public,Middle,24890.74,72.8,27.0,58.1,35.8,51.1,14.75
3,4,Weaver High School,Texas,Private,Elementary,6857.49,81.5,26.2,82.7,72.0,55.5,13.45
4,5,King Elementary School,Michigan,Public,Elementary,16910.73,44.7,20.2,41.4,16.1,57.8,6.98
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Hale High School,Ohio,Charter,Elementary,8775.63,51.9,18.3,12.9,61.0,50.5,10.03
996,997,Herrera Elementary School,Georgia,Public,High,24440.93,61.1,19.2,24.8,49.1,89.3,3.11
997,998,Combs High School,New York,Private,Middle,23947.18,94.2,25.2,16.7,51.1,55.8,7.14
998,999,Buckley Elementary School,Illinois,Private,Elementary,6459.87,57.0,17.0,73.6,48.4,64.0,1.21
999,1000,Berg Elementary School,Illinois,Private,Elementary,15471.48,51.6,10.9,31.1,83.9,94.2,1.53

# Tratamento e limpeza dos dados

Para começar, vamos verificar os tipos de dados que temos em nosso dataframe, quantidade de colunas e quantidade de dados

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       1000 non-null   int64
 1   school_name              1000 non-null   object
 2   state                    1000 non-null   object
 3   school_type              1000 non-null   object
 4   grade_level              1000 non-null   object
 5   funding_per_student_usd  1000 non-null   float64
 6   avg_test_score_percent   1000 non-null   float64
 7   student_teacher_ratio    1000 non-null   float64
 8   percent_low_income       1000 non-null   float64
 9   percent_minority         1000 non-null   float64
 10  internet_access_percent  1000 non-null   float64
 11  dropout_rate_percent     1000 non-null   float64
dtypes: float64(7), int64(1), object(4)
memory usage: 93.9+ KB

  Em nosso banco de dados, temos o total de 12 colunas, com 1.000 entrada de dados e com seus dados divididos em object, int e float

Tendo as informações gerais sobre o banco de dados, agora vamos verificar se existem valores nulos ou registros duplicados.

In [50]:
verificar_nulos = df.isnull().sum()
display(verificar_nulos)

id                         0
school_name                0
state                      0
school_type                0
grade_level                0
funding_per_student_usd    0
avg_test_score_percent     0
student_teacher_ratio      0
percent_low_income         0
percent_minority           0
internet_access_percent    0
dropout_rate_percent       0
dtype: int64

In [51]:
verificar_duplicados = df.duplicated().sum()
display(verificar_duplicados)

np.int64(0)

Podemos visualizar que em nosso banco de dados não existe valores nulos/faltantes ou duplicados

Agora vamos renomear as colunas para melhor entendimento

In [52]:
df.rename(columns= {
    "school_name":"Nome da escola",
    "state":"Estado",
    "school_type":"Tipo de instituição",
    "grade_level":"Nível escolar",
    "funding_per_student_usd":"Financiamento por aluno US",
    "avg_test_score_percent":"Desempenho do aluno",
    "student_teacher_ratio":"Alunos por professor",
    "percent_low_income":"Estudantes de baixa renda",
    "percent_minority":"Origens minoritárias",
    "internet_access_percent":"Acesso à internet (%)",
    "dropout_rate_percent":"Evasão Escolar (%)"
}, inplace=True)

display(df)

,id,Nome da escola,Estado,Tipo de instituição,Nível escolar,Financiamento por aluno US,Desempenho do aluno,Alunos por professor,Estudantes de baixa renda,Origens minoritárias,Acesso à internet (%),Evasão Escolar (%)
0,1,Bowman High School,Michigan,Private,High,9575.80,65.9,17.5,30.0,44.0,74.1,3.44
1,2,Foster High School,Michigan,Charter,Middle,16733.10,87.3,24.2,93.5,40.1,79.9,8.67
2,3,Henson High School,New York,Public,Middle,24890.74,72.8,27.0,58.1,35.8,51.1,14.75
3,4,Weaver High School,Texas,Private,Elementary,6857.49,81.5,26.2,82.7,72.0,55.5,13.45
4,5,King Elementary School,Michigan,Public,Elementary,16910.73,44.7,20.2,41.4,16.1,57.8,6.98
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Hale High School,Ohio,Charter,Elementary,8775.63,51.9,18.3,12.9,61.0,50.5,10.03
996,997,Herrera Elementary School,Georgia,Public,High,24440.93,61.1,19.2,24.8,49.1,89.3,3.11
997,998,Combs High School,New York,Private,Middle,23947.18,94.2,25.2,16.7,51.1,55.8,7.14
998,999,Buckley Elementary School,Illinois,Private,Elementary,6459.87,57.0,17.0,73.6,48.4,64.0,1.21
999,1000,Berg Elementary School,Illinois,Private,Elementary,15471.48,51.6,10.9,31.1,83.9,94.2,1.53

Agora que modificamos os nomes das colunas, vamos remover algumas colunas que não serão necessárias em nossa análise, sendo elas: a coluna id e a coluna Nome da escola

In [53]:
df.drop(columns={
    "id",
    "Nome da escola"
}, inplace=True)

display(df)

,Estado,Tipo de instituição,Nível escolar,Financiamento por aluno US,Desempenho do aluno,Alunos por professor,Estudantes de baixa renda,Origens minoritárias,Acesso à internet (%),Evasão Escolar (%)
0,Michigan,Private,High,9575.80,65.9,17.5,30.0,44.0,74.1,3.44
1,Michigan,Charter,Middle,16733.10,87.3,24.2,93.5,40.1,79.9,8.67
2,New York,Public,Middle,24890.74,72.8,27.0,58.1,35.8,51.1,14.75
3,Texas,Private,Elementary,6857.49,81.5,26.2,82.7,72.0,55.5,13.45
4,Michigan,Public,Elementary,16910.73,44.7,20.2,41.4,16.1,57.8,6.98
...,...,...,...,...,...,...,...,...,...,...
995,Ohio,Charter,Elementary,8775.63,51.9,18.3,12.9,61.0,50.5,10.03
996,Georgia,Public,High,24440.93,61.1,19.2,24.8,49.1,89.3,3.11
997,New York,Private,Middle,23947.18,94.2,25.2,16.7,51.1,55.8,7.14
998,Illinois,Private,Elementary,6459.87,57.0,17.0,73.6,48.4,64.0,1.21
999,Illinois,Private,Elementary,15471.48,51.6,10.9,31.1,83.9,94.2,1.53

# Métricas Estatísticas